// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingOnline.Context;

namespace ShoppingOnline.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20200818065749_AddedSeedProducts2")]
    partial class AddedSeedProducts2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.7.20365.15");

            modelBuilder.Entity("ShoppingOnline.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CodeProduct")
                        .HasColumnType("int");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CodeProduct = -44900,
                            Discount = 100.0,
                            Name = "Xiaomi Redmi 8A",
                            Price = 2099.0
                        },
                        new
                        {
                            ID = 2,
                            CodeProduct = -36726,
                            Discount = 2000.0,
                            Name = "Apple iPhone XS",
                            Price = 14499.0
                        },
                        new
                        {
                            ID = 3,
                            CodeProduct = -45833,
                            Discount = 200.0,
                            Name = "Samsung Galaxy A71 A715",
                            Price = 8299.0
                        },
                        new
                        {
                            ID = 4,
                            CodeProduct = -44894,
                            Discount = 0.0,
                            Name = "Samsung Galaxy M30s M307",
                            Price = 4999.0
                        },
                        new
                        {
                            ID = 5,
                            CodeProduct = -44505,
                            Discount = 3500.0,
                            Name = "Asus Zenfone 6 ZE630KL",
                            Price = 9999.0
                        },
                        new
                        {
                            ID = 6,
                            CodeProduct = -44330,
                            Discount = 1500.0,
                            Name = "Sony Xperia 1 J9110",
                            Price = 15499.0
                        },
                        new
                        {
                            ID = 7,
                            CodeProduct = -36479,
                            Discount = 100.0,
                            Name = "Nokia 5.1",
                            Price = 1999.0
                        });
                });

            modelBuilder.Entity("ShoppingOnline.Models.ProductDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AccumulatorBattery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayDiagonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMemoryCardSupport")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWiFi")
                        .HasColumnType("bit");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("RearCamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenMatrixType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondChamber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("ProductDetail");
                });

            modelBuilder.Entity("ShoppingOnline.Models.ProductPicture", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPicture");
                });

            modelBuilder.Entity("ShoppingOnline.Models.Profile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRef")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserRef")
                        .IsUnique();

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("ShoppingOnline.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ShoppingOnline.Models.ProductDetail", b =>
                {
                    b.HasOne("ShoppingOnline.Models.Product", "Product")
                        .WithOne("ProductDetail")
                        .HasForeignKey("ShoppingOnline.Models.ProductDetail", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShoppingOnline.Models.ProductPicture", b =>
                {
                    b.HasOne("ShoppingOnline.Models.Product", "Product")
                        .WithMany("ProductPictures")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShoppingOnline.Models.Profile", b =>
                {
                    b.HasOne("ShoppingOnline.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("ShoppingOnline.Models.Profile", "UserRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
